name: Renovate
on:
  push:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: .github/renovate-config.json5
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
