name: Renovate
on:
  push:
  schedule:
    # minute hour dayOfmonth mounth dayOfWeek
    - cron: "0/5 3 * * 0" # Sunday
    - cron: "0/15 4 * * 0" # Sunday
    - cron: "0 5-20 * * 0" # Sunday
    - cron: "0 8-20 * * 1-5" # week days
    - cron: "0 8-20 * * 6" # Saturday
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.198.1
        with:
          configurationFile: .github/renovate-config.json5
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
